// nextjs-frontend/components/form/BaseTextField.tsx
'use client'

interface BaseTextFieldProps {
  modelValue: string | number
  label: string
  placeholder?: string
  hint?: string
  type?: string
  error?: string
  onChange?: (value: string | number) => void
}

export default function BaseTextField({
  modelValue,
  label,
  placeholder = '',
  hint = '',
  type = 'text',
  error = '',
  onChange,
}: BaseTextFieldProps) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-600 px-8 py-5">
      <label className="block text-sm font-semibold text-[#163B52] dark:text-cyan-300 mb-4">
        {label}
      </label>

      <div className="relative">
        <input
          type={type}
          placeholder={placeholder}
          value={modelValue}
          onChange={(e) => onChange?.(e.target.value)}
          className="w-full bg-transparent outline-none border-0 border-b border-slate-300 dark:border-slate-500 pb-1 text-sm text-slate-800 dark:text-slate-100 placeholder-slate-400 dark:placeholder-slate-500"
        />

        {hint && !error && (
          <p className="mt-1 text-[11px] text-slate-400 dark:text-slate-500">
            {hint}
          </p>
        )}
        {error && (
          <p className="mt-1 text-xs text-red-500">
            {error}
          </p>
        )}
      </div>
    </div>
  )
}

// src/components/form/BaseTextField.vue
<template>
  <div class="bg-white rounded-2xl shadow-sm border border-slate-100 px-8 py-5">
    <label class="block text-sm font-semibold text-[#163B52] mb-4">
      {{ label }}
    </label>

    <div class="relative">
      <input
        :type="type"
        :placeholder="placeholder"
        v-model="model"
        class="w-full bg-transparent outline-none border-0 border-b border-slate-300 pb-1 text-sm text-slate-800"
      />
      <p v-if="hint && !error" class="mt-1 text-[11px] text-slate-400">
        {{ hint }}
      </p>
      <p v-if="error" class="mt-1 text-xs text-red-500">
        {{ error }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  modelValue: {
    type: [String, Number],
    default: ''
  },
  label: {
    type: String,
    required: true
  },
  placeholder: {
    type: String,
    default: ''
  },
  hint: {
    type: String,
    default: ''
  },
  type: {
    type: String,
    default: 'text'
  },
  error: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['update:modelValue'])

const model = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val)
})
</script>
