// nextjs-frontend/components/FlashesCategoryLayout.tsx
import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import BaseLayout from './BaseLayout'
import Breadcrumb from './Breadcrumb'

interface Video {
  id: number
  slug: string
  title: string
  image: string
  duration?: string
}

interface FlashesCategoryLayoutProps {
  title: string
  breadcrumbLabel: string
  description?: string
  videos: Video[]
  categorySlug: string
}

const FlashesCategoryLayout: React.FC<FlashesCategoryLayoutProps> = ({
  title,
  breadcrumbLabel,
  description = '',
  videos,
  categorySlug,
}) => {
  return (
    <BaseLayout>
      <div className="mx-auto mt-12 max-w-[1300px] px-4 pb-20" dir="rtl">
        <Breadcrumb
          items={[
            { label: 'الرئيسية', href: '/' },
            { label: 'قسم الإعلام والتوعية', href: '/media' },
            { label: 'فلاشات توعوية', href: '/media/flashes' },
            { label: breadcrumbLabel },
          ]}
        />

        <div className="mx-auto max-w-[1300px] px-4 mb-6 text-right">
          <h1 className="text-3xl font-bold text-[#000000] dark:text-cyan-300 mb-3">
            {title}
          </h1>
          {description && (
            <p className="text-gray-600 dark:text-slate-300 mb-8 leading-relaxed max-w-[850px] ml-auto">
              {description}
            </p>
          )}
        </div>

        <div className="mx-auto max-w-[1300px] bg-white dark:bg-slate-900 rounded-[40px] border border-[#E5EDF0] dark:border-slate-700 shadow-sm px-6 md:px-10 py-10">
          <div className="grid md:grid-cols-2 gap-8">
            {videos.map((video) => (
              <Link
                key={video.id}
                href={`/media/flashes/${categorySlug}/${video.slug}`}
                className="group relative rounded-3xl overflow-hidden bg-slate-900/80 shadow-sm border border-[#E3EFF1] dark:border-slate-700 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 block"
              >
                <Image
                  src={video.image}
                  alt={video.title}
                  width={600}
                  height={280}
                  className="w-full h-[260px] md:h-[280px] object-cover group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute inset-0 bg-black/35 group-hover:bg-black/45 flex flex-col justify-between">
                  <div className="flex justify-end items-start p-3 text-xs text-white/80">
                    {video.duration && (
                      <span className="px-2 py-1 rounded-full bg-black/40 backdrop-blur">
                        {video.duration}
                      </span>
                    )}
                  </div>

                  <div className="flex-1 flex items-center justify-center">
                    <div className="w-14 h-14 rounded-full bg-white/90 text-[#165C75] flex items-center justify-center shadow-lg group-hover:scale-110 group-hover:shadow-2xl transition-transform duration-300">
                      <svg className="w-6 h-6" viewBox="0 0 24 24" fill="none">
                        <path d="M9 7v10l8-5-8-5Z" fill="currentColor" />
                      </svg>
                    </div>
                  </div>

                  <div className="p-4 pt-3 pb-2 bg-gradient-to-t from-black/60 to-black/0">
                    <h3 className="text-white font-bold text-xl md:text-2xl leading-8 line-clamp-2 group-hover:text-[#7BD4FF] transition-colors mb-0">
                      {video.title}
                    </h3>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </div>
    </BaseLayout>
  )
}

export default FlashesCategoryLayout

// src/components/FlashesCategoryLayout.vue
<template>
  <div class="bg-[#F8FBFC] pb-20">
    <div class="mx-auto max-w-[1300px] px-4 mt-12" dir="rtl">

      <!-- 🧭 Breadcrumb -->
      <div class="mx-auto max-w-[1300px] px-4 mt-4 mb-4">
        <nav class="text-slate-500 text-sm flex items-center gap-2">
          <RouterLink to="/" class="hover:text-[#165C75]">الرئيسية</RouterLink>
          <span>›</span>
          <RouterLink to="/media" class="hover:text-[#165C75]">
            قسم الإعلام والتوعية
          </RouterLink>
          <span>›</span>
          <RouterLink to="/media/flashes" class="hover:text-[#165C75]">
            فلاشات توعوية
          </RouterLink>
          
          <span>›</span>
          <span class="text-[#165C75] font-semibold">
            {{ breadcrumbLabel }}
          </span>
        </nav>
      </div>

      <!-- 🟦 عنوان الصفحة (يمين زي ما تحبي) -->
      <div class="mx-auto max-w-[1300px] px-4 mb-6 text-right">
        <h1 class="text-3xl font-bold text-[#165C75] mb-2">
          {{ title }}
        </h1>
        <p
          v-if="description"
          class="text-slate-600 text-lg leading-8 w-full md:w-[80%] ml-auto"
        >
          {{ description }}
        </p>
      </div>

      <!-- 🟩 الكارد الأبيض الكبير -->
      <div
        class="mx-auto max-w-[1300px] bg-white rounded-[40px] border border-[#E5EDF0]
               shadow-sm p-6 md:p-10"
      >
        <!-- شبكة الفيديوهات -->
        <div class="grid md:grid-cols-2 gap-8">
          <RouterLink
            v-for="video in videos"
            :key="video.id"
            :to="{
              name: 'media-flash-detail',
              params: { category: categorySlug, slug: video.slug }
            }"
            class="bg-white rounded-[32px] border border-[#E3EFF1] shadow-sm
                   overflow-hidden cursor-pointer hover:shadow-md
                   transition-shadow duration-200 block"
          >
            <!-- البوستر -->
            <div class="w-full h-[260px] md:h-[280px] overflow-hidden">
              <img
                :src="video.image"
                :alt="video.title"
                class="w-full h-full object-cover"
              />
            </div>

            <!-- شريط العنوان السماوي -->
            <div class="bg-[#D9F2F4] px-6 py-4 flex items-center justify-center">
              <h3
                class="text-[#165C75] text-lg md:text-xl font-bold leading-8 text-center"
              >
                {{ video.title }}
              </h3>
            </div>
          </RouterLink>
        </div>
      </div>

    </div>
  </div>
</template>

<script setup>
import { RouterLink } from 'vue-router'

const props = defineProps({
  title: { type: String, required: true },
  breadcrumbLabel: { type: String, required: true },
  description: { type: String, default: '' },
  videos: { type: Array, required: true }, // [{id,title,image,slug}]
  categorySlug: { type: String, required: true }, // 👈 جاي من MediaFlashesCategory.vue
})
</script>
